name: deploy on push
on: 
    push:
      branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v4
      - name: copy file to sever
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST }}
          username: ${{secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./html/*"
          target: "/var/www/html/"
          strip_components: 1

  